;/etc/supervisor/conf.d/messenger-worker.conf
[program:messenger-consume]
command=php /var/www/html/bin/console messenger:consume doctrine --time-limit=3600 --memory-limit=128M
user=root
numprocs=1
autostart=true
autorestart=true
startretries=3
stopwaitsecs=10
stdout_logfile=/var/log/supervisor/doctrine-queue-worker.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/doctrine-queue-worker-error.log
stderr_logfile_maxbytes=50MB
process_name=%(program_name)s_%(process_num)02d

